AWSTemplateFormatVersion: 2010-09-09
Description: "EY Project RDS Template"

Parameters:
  ApplicationName:
    Description: "App name"
    Type: String
    Default: "EY"

  Environment:
    Description: "Application Environment"
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "test", "stage", "prod"]

  Contact:
    Description: "Contact Email For The Team"
    Type: String

  DBName:
    Default: mydb
    Description: Name of Database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters

  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.

  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.

  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

Resources: 
  RDSDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Join [ "-", [!Ref ApplicationName, !Ref Environment, "RDS"] ]
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: "8.0.32"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups: 
        - !ImportValue 
          Fn::Sub: "${ApplicationName}-${Environment}-DBSecurityGroupID"
      DBSubnetGroupName: !Ref DBSubnetGroup


  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup" 
    Properties: 
      DBSubnetGroupDescription: "Private Subnet Group To Launch RDS"
      SubnetIds: 
        - !ImportValue 
          Fn::Sub: "${ApplicationName}-${Environment}-PrivateSubnet1ID"
        - !ImportValue 
          Fn::Sub: "${ApplicationName}-${Environment}-PrivateSubnet2ID"
      Tags:
        - Key: Name
          Value: !Join [ "-", [!Ref ApplicationName, !Ref Environment, "DBSubnetGroup"] ]
        - Key: App
          Value: !Ref ApplicationName
        - Key: Env
          Value: !Ref Environment
        - Key: Contact
          Value: !Ref Contact
